# Generated by Django 5.0 on 2024-01-29 09:34

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_student_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="IAF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("sector", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "opening_date",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("closing_date", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Signed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.SmallIntegerField()),
                (
                    "iaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.iaf"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.student"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="signed",
            constraint=models.UniqueConstraint(
                fields=("iaf", "student"), name="iaf_student_combination"
            ),
        ),
    ]
