# Generated by Django 5.0 on 2024-01-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_iaf_signed_signed_iaf_student_combination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iaf",
            name="status",
        ),
        migrations.AlterField(
            model_name="signed",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unsigned", "Unsigned"),
                    ("Signed", "Signed"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                max_length=30,
            ),
        ),
    ]
